---
# This file contains the parameters for the training and testing of the model.

# WandB parameters, can be ignored if not using WandB
wandb_training_project: "sa-net"
wandb_training_name: "swellex-run-newbeta-1"
run_with_wandb: false

# Training parameters
batch_size: 32
sample_duration: 1.0
data_format_mode: "time_series" # (Accepted: "time_series", "chunked_list")
audio_channels: 21
learning_rate: 1e-4
num_epochs: 3500
device: "cuda" # (Accepted: "cuda", "cpu")
optimizer: "Adam"
sampling_rate: 1500
list_of_chunks_mode: false
num_samples: 4500
# Only used if simulated_data_mode = true
# This is the number of samples to process for the simulated dataset
simulated_num_samples: 4960 

# Multiple datasets - experiment, when used, provide the dataset paths below
multiple_datasets_mode: false 
train_datasets: []
validation_datasets: []
test_datasets: []

# The following parameters are for the single dataset path mode
# if cross_validation_mode = true, provide the total_folds, train_folds, validation_folds, and test_folds
# if cross_validation_mode = false, provide the test_size
# use either mode only, not both, when one mode is used, the other parameter is ignored
cross_validation_mode: true
total_folds: 6
train_folds: [0,1,2,3]
validation_folds: [4]
test_folds: [5]
test_size: 0.9
run_inference_mode: true
finetune_mode: false # If finetune_mode = true, pretrained_model_path must be provided
log_verbose: false
print_first_10th_predictions: false
prediction_output_image_plot: "true_vs_predicted_labelsS5-VLA.png"
csv_file_path: "data/vla_raw.csv"
sproul_text_file_path: "data/SproulToVLA.S5.txt"
best_model_path: "best_model-scratch-s5-VLA.pth"
parallel_mode: false
simulated_data_mode: false
data_augmentation: false # accepted values: false, "noise", "time_warp", "polarity_flip", "mixup", "all_augment"
pretrained_model_path: "model_checkpoints/best_model-scratch-s5-VLA-10pc.pth" # Only needed if finetune_mode is true
dataset_path: "./swellex-6folds-real-physics.pkl"
save_dir: "model_checkpoints"
